import { ReactNode } from "react";

export interface ChildrenProps {
  children: ReactNode;
}

export interface UserDetailsFromGoogle {
  displayName: string;
  email: string;
  phoneNumber: number;
  photoURL: string;
  uid: string;
}
export interface UserDetailsFromSite {
  phoneNumber: number;
  college: string;
  graduationYear: number;
  course: string;
  dob: string;
  gender: string;
  address: string;
  state: string;
  pinCode: number;
}

export interface UserDetailsAutoGenerated {
  qrCodeUrl: string;
  createdAt: string;
}

export interface User extends UserDetailsFromGoogle, UserDetailsFromSite, UserDetailsAutoGenerated {
  // merch: string;
  orders: [];
  score: string;
  eventRegistered: [];
}
